[package]
name = "abstrie_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "abstrie_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
abstrie_core = { path = "../../abstrie_core" }
